export const MENU_KEYS = {
  DASHBOARD: "DASHBOARD",
  CONFIG_USUARIOS: "CONFIG_USUARIOS",
  CONFIG_ROLES: "CONFIG_ROLES",
  CONFIG_GENERAL: "CONFIG_GENERAL",
  CONFIG_MENU: "CONFIG_MENU",
  CONFIG_CONDUCTORES: "CONFIG_CONDUCTORES",
  INSPECCION_DIARIA: "INSPECCION_DIARIA",
  PERFIL_PROPIO: "PERFIL_PROPIO",
} as const;
