export const MENU_KEYS = {
  DASHBOARD: "DASHBOARD",
  CONFIG_USUARIOS: "CONFIG_USUARIOS",
  CONFIG_ROLES: "CONFIG_ROLES",
  CONFIG_GENERAL: "CONFIG_GENERAL",
  CONFIG_MENU: "CONFIG_MENU",
} as const;
